### ISSUE TITLE
Feature Improvement List & ToDo's

### ISSUE THREAD

**Issue by Knowledge-Wisdom-Understanding** [Knowledge-Wisdom-Understanding/recon#4]
# Feature Improvement List & ToDo's

### Multiprocessing Pool

- [ ] 1. Multiprocessing Implementation [Utils/run_commands.py](../tree/master/utils/run_commands.py)
There is always a better way to get things done and I'm sure my current implementation of multiprocessing's pool method can / should be optimized. I'm not sure what the best way would be to improve the current implementation. 
I've pondered whether it would make more sense to run all tasks asynchronously / using different multiprocessing's methods etc.. 
It might make more sense to add a queue to this function but I haven't gotten around to figuring out the optimal way of setting this up yet. 🐍 
referring to the code, mpRun() function in [run_commands.py](../tree/master/utils/run_commands.py) handles most Pool'd Command processes.
```python
class RunCommands:
    """Helper Class to Wrap all commands in easy to access functions that can be called easily."""

    def __init__(self, target):
        self.target = target
        # self.run_commands_parent_pid = os.getpid()

    def loginator(self, executed_command):
        c = config_parser.CommandParser(f"{os.getcwd()}/config/config.yaml", self.target)
        logging.basicConfig(
            filename=c.getPath("report", "log"),
            format='%(asctime)s %(message)s',
            datefmt='%m/%d/%Y %I:%M:%S %p',
            level=logging.INFO
        )
        logging.info(f"[+] {executed_command}")

    def mpRun(self, commands):
        """Pool all commands to run from each service class and run them 2 at a time.,"""
        if len(commands) != 0:
            parent_id = os.getpid()

            def worker_init():
                def sig_int(signal_num, frame):
                    parent = psutil.Process(parent_id)
                    for child in parent.children():
                        if child.pid != os.getpid():
                            # print("Killing child process: ", child.pid)
                            child.kill()
                    # print("Killing Parent Process ID: ", parent.pid())
                    parent.kill()
                    psutil.Process(os.getpid()).kill()
                signal.signal(signal.SIGINT, sig_int)

            green = fg.li_green
            reset = fg.rs
            with Pool(2, worker_init) as p:
                try:
                    max_ = len(commands)
                    with tqdm(total=max_) as pbar:
                        for i, returncode in enumerate(
                            p.imap_unordered(partial(call, shell=True), commands)
                        ):
                            pbar.update()
                            pbar.write(f"[{green}+{reset}] {green}{commands[i]}{reset}")
                            pbar.set_description_str(desc=f"{fg.li_yellow}{commands[i].split()[:1]}{fg.rs}")
                            self.loginator(commands[i])
                            if returncode != 0:
                                print(f"{i} command failed: {returncode}")
                except KeyboardInterrupt:
                    p.close()
                    p.terminate()
                    p.join()
```

- [ ] 2. SIGINT CTRL+C KEYBOARD-INTERRUPT
Currently I have a signal handler in [recon.py](../tree/master/recon.py) __main__
```python
def signal_handler(sig, frame):
    print(" ")
    print(f"{purp}See you Space Cowboy...{reset}")
    print(" ")
    sys.exit(0)
```
```python
if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    main()
```
to catch CTRL+C keyboard interruptions. I've also added a signal handler to mpRun & mpRunSploit in [Utils/run_commands.py](../tree/master/utils/run_commands.py)
```python
            parent_id = os.getpid()
            def worker_init():
                def sig_int(signal_num, frame):
                    parent = psutil.Process(parent_id)
                    for child in parent.children():
                        if child.pid != os.getpid():
                            # print("Killing child process: ", child.pid)
                            child.kill()
                    # print("Killing Parent Process ID: ", parent.pid())
                    parent.kill()
                    psutil.Process(os.getpid()).kill()
                signal.signal(signal.SIGINT, sig_int)
```
```python
with Pool(2, worker_init) as p:
        try:
                ...
```
However, If CTRL+C is pressed during the run_commands.py multiprocessing's Pool, Things processes don't always exit / stop gracefully.
For example, if dirsearch.py is running and you press CTRL+C, it won't always quit completely.
Normally when running dirsearch from the CLI , if you press CTRL+C, dirsearch will prompt you if you really want to quit, or continue etc.. As it stands, I'm not sure how to handle SIGINT CTRL+C during the Pool'd processes run time so as to allow process interaction with tools such as dirsearch that accept ctrl+c to quit dirsearch but continue running the rest of the recon.py scans and enumeration.

 - [ ] 3. STDOUT Command Printing Formatting & Organization
Most stdout from various commands are displayed in the terminal verbosely as they're ran. This output won't always look the prettiest however, all output is logged cleanly to their respective report structures.
For instance, during web enumeration, a pool of 6 + commands are being run 2 at a time in mpRun() on line 51 which can cause standard output to get a little mixed up, Especially while 2 directory traversal tools are ran simultaneously.
I thought about running 🏃  the commands 1 at a time which would definitely make std out much prettier, however I prefer the performance/faster scanning completion time over 1 by 1 organized output. 🔧 
Previously, I had added extra echo commands for each web command  as can be seen in this old commit dd29a6419f125d99cc36f3f2ad4ba927ded3e093 etc.. so that the command would print nicely right before the command was ran. This worked however, this caused the code to become subjectively uglier and much longer.
Commands will still be printed as their running via tqdm's progressbar.write method.
```python
pbar.update()
pbar.write(f"[{green}+{reset}] {green}{commands[i]}{reset}")
pbar.set_description_str(desc=f"{fg.li_yellow}{commands[i].split()[:1]}{fg.rs}")
```
Due to the current implementation of [run_commands.py](../tree/master/utils/run_commands.py), commands now get printed after the command has been run sometimes.
Not a huge deal, but it would be nice to improve this minor defect. If anyone want's to contribute to this project, that would be pretty cool.

### Feature Requests & or Tool Suggestion's and Functionality
- A list of all tools and their subsequent command syntax can be viewed / configured
in the [Config.yaml](../tree/master/config/config.yaml) file. 🔨 

#### Feel free to comment your thoughts about the project

Any Constructive Criticism is much appreciated. If you have any ideas on how to make this project better, Let me Know! Peace! 💎
